### ISSUE TITLE
ccc 1.8 一加载控制台就报红。但好像不影响

### ISSUE THREAD

**Issue by 0x0000000000000000000000000** [oyb81076/cocos-mobx-demo#3]
[mobx] Deprecated: Deprecated value for 'enforceActions', use 'false' => '"never"', 'true' => '"observed"', '"strict"' => "'always'" instead

**Comment by oyb81076** [comment]
好像是mobx版本问题
assets/scripts/observer.ts
mobx.configure({ enforceActions: "always" })
