### ISSUE TITLE
项目在ccc2.0.9 跑起来时候 控制台有一堆报错

### ISSUE THREAD

**Issue by doerme** [oyb81076/cocos-mobx-demo#4]
Cocos Services load base data!
load script [./socket] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: SocketStore@1.loading
load script [./canvas] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: CanvasStore@3.base
load script [/Users/liangxiaoming/Documents/cocos_creator/shooter/cocos-mobx-demo/temp/quick-scripts/assets/complex/stores/canvas.js] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: CanvasStore@7.base
load script [/Users/liangxiaoming/Documents/cocos_creator/shooter/cocos-mobx-demo/temp/quick-scripts/assets/complex/stores/socket.js] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: SocketStore@11.loading
load script [./store] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Store@13.total
load script [./store] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Store@15.total
 
A Class already exists with the same __classname__ : "store".
 
A Class already exists with the same __cid__ : "1973aHYiElOK4Nh2aZrpahT".
load script [./store] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Store@17.total
 
A Class already exists with the same __classname__ : "store".
 
A Class already exists with the same __cid__ : "1973aHYiElOK4Nh2aZrpahT".
load script [./store] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Store@19.total
 
A Class already exists with the same __classname__ : "store".
 
A Class already exists with the same __cid__ : "1973aHYiElOK4Nh2aZrpahT".
load script [/Users/liangxiaoming/Documents/cocos_creator/shooter/cocos-mobx-demo/temp/quick-scripts/assets/simple/store.js] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: Store@21.total
 
Script attached to "Canvas" in scene "complex.fire" is missing or invalid. Detailed information:
 
Error: Uuid Loader: Deserialize asset [ /Users/liangxiaoming/Documents/cocos_creator/shooter/cocos-mobx-demo/library/imports/65/653f919b-68e5-490e-982d-c10d07f879f0.json ] failed : Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: class_1@23.id
 
TypeError: Cannot convert object to primitive value

**Comment by oyb81076** [comment]
代码当时是用 5.0.1 版本的mobx，更新版本的mobx没调试过。

**Comment by oyb81076** [comment]
先把mobx降到5.0.0版本就能正常，使用最新版本的需要调一下这里的代码

**Comment by oyb81076** [comment]
已经调整了，是因为mobx新版本对mobx.configure 的一些调整导致的。
