### ISSUE TITLE
请问在native上使用mobx该怎么导入

### ISSUE THREAD

**Issue by sevenvip** [oyb81076/cocos-mobx-demo#5]
这个只能在web上运行吧，如果在native 怎么使用 mobx。

**Comment by oyb81076** [comment]
native cocos也会打包进去的，如果是正式版的话 mobx版本用 4.13.0版本，因为5.x版本在 ios9.x版本下无法运行

**Comment by sevenvip** [comment]
@oyb81076 刚才试了一下确实是这样，感谢。
